server:
  port: 80
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
      force-response: true
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1 from dual
      connection-timeout: 60000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 15
      minimum-idle: 5
      pool-name: HikariCP
      read-only: false
      validation-timeout: 3000
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/manager?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=true
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  mvc:
    static-path-pattern: /static/**
logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug